### ISSUE TITLE
Error compiling algo crate for Rust

### ISSUE THREAD

**Issue by KittyTechnoProgrammer** [correlation-one/C1GamesStarterKit#106]
When ever I try to build my algo using build_local.py. I get these errors from the compiler. From my understanding. This seems to be in the algo library it's self (correct me if I'm wrong).

OS: Linux
Excepted: Compiled binary 

"   Compiling algo v0.1.0 (/home/kittytechno/Downloads/C1GamesStarterKit-master/rust-algo/algo)
error[E0599]: no function or associated item named `info_units` found for struct `map::MapTileInner` in the current scope
   --> algo/src/map/mod.rs:281:25
    |
78  | pub struct MapTileInner {
    | ----------------------- function or associated item `info_units` not found for this
...
281 |         } else if Self::info_units(c, map).len() > 0 {
    |                         ^^^^^^^^^^ function or associated item not found in `map::MapTileInner`

error[E0599]: no method named `into_info` found for enum `units::SpawnableUnitType` in the current scope
   --> algo/src/map/mod.rs:377:42
    |
377 |                     unit_type: unit_type.into_info().unwrap(),
    |                                          ^^^^^^^^^ method not found in `units::SpawnableUnitType`
    | 
   ::: algo/src/units.rs:143:1
    |
143 | pub enum SpawnableUnitType {
    | -------------------------- method `into_info` not found for this

error[E0609]: no field `Demolisher` on type `&PlayerUnits`
  --> algo/src/map/parse.rs:30:54
   |
30 |                 MobileUnitType::Demolisher => &units.Demolisher,
   |                                                      ^^^^^^^^^^ help: a field with a similar name exists: `demolisher`

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0599, E0609.
For more information about an error, try `rustc --explain E0599`.
error: could not compile `algo`

To learn more, run the command again with --verbose.
Traceback (most recent call last):
  File "/home/kittytechno/Downloads/C1GamesStarterKit-master/rust-algo/build_local.py", line 88, in <module>
    result = compile_rust()
  File "/home/kittytechno/Downloads/C1GamesStarterKit-master/rust-algo/build_local.py", line 57, in compile_rust
    subprocess.check_output(command)
  File "/usr/lib/python3.9/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cargo', 'build', '--package', 'starter-algo', '--bin', 'starter-algo']' returned non-zero exit status 101."

**Comment by KittyTechnoProgrammer** [comment]
I've seen Algos written in rust, but I don't know if they fixed it themselves, or if they used an older version of the crate.

**Comment by KittyTechnoProgrammer** [comment]
It works now. Thank you.
