### ISSUE TITLE
Java version mismatch

### ISSUE THREAD

**Issue by matteosantama** [correlation-one/C1GamesStarterKit#127]
I am getting the error

```
❯ python3 ./scripts/run_match.py python-algo/algo-target python-algo/algo-target
Is windows: False
Algo 1:  python-algo/algo-target/run.sh
Algo 2: python-algo/algo-target/run.sh
Start run a match
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/c1games/terminal/Terminal has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:620)
Finished running match
```

I am running on Mac M1, how can I fix this?

**Comment by matteosantama** [comment]
Ah, was able to update my runtime at [this](https://www.oracle.com/java/technologies/downloads/#java11) link
