### ISSUE TITLE
Error when running run_match.ps1 on Windows

### ISSUE THREAD

**Issue by BouncyMaster** [correlation-one/C1GamesStarterKit#28]
I have Windows 7 64bit with JRE and JDK both 10.0.2 and Python 3.6.6. When i try to run scripts\run_match.ps1 algos\starter-algo algos\starter-algo in PowerShell i get this output:

```
p1:
algos\starter-algo\run.ps1
p2:
algos\starter-algo\run.ps1
Starting Engine
Starting single worker game.
algos\starter-algo\run.ps1
algos\starter-algo\run.ps1
Saving replay: D:\NICU\C1GamesStarterKit-master\replays\p1-04-10-2018-22-46-49-1538682409900-60714274.replay
P1 Name: starter-algo
P2 Name: starter-algo
Starting turn: 0
SAPlayer 1 starter-algo: Split-Path : Cannot bind argument to parameter 'Path' because it is null.
SAPlayer 1 starter-algo: At D:\NICU\C1GamesStarterKit-master\algos\starter-algo\run.ps1:1 char:25
SAPlayer 1 starter-algo: + $scriptPath = Split-Path <<<<  -parent $PSCommandPath;
SAPlayer 1 starter-algo:     + CategoryInfo          : InvalidData: (:) [Split-Path], ParameterBindingV
SAPlayer 1 starter-algo:    alidationException
SAPlayer 1 starter-algo:     + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,M
SAPlayer 1 starter-algo:    icrosoft.PowerShell.Commands.SplitPathCommand
SAPlayer 1 starter-algo:
SAPlayer 2 starter-algo: Split-Path : Cannot bind argument to parameter 'Path' because it is null.
SAPlayer 2 starter-algo: At D:\NICU\C1GamesStarterKit-master\algos\starter-algo\run.ps1:1 char:25
SAPlayer 2 starter-algo: + $scriptPath = Split-Path <<<<  -parent $PSCommandPath;
SAPlayer 2 starter-algo:     + CategoryInfo          : InvalidData: (:) [Split-Path], ParameterBindingV
SAPlayer 2 starter-algo:    alidationException
SAPlayer 2 starter-algo:     + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,M
SAPlayer 2 starter-algo:    icrosoft.PowerShell.Commands.SplitPathCommand
SAPlayer 2 starter-algo:
timed out
timed out
Last state:
Last state:
{"p2Units":[[],[],[],[],[],[],[]],"turnInfo":[0,0,-1],"p1Stats":[30.0,25.0,5.0,0],"p1Units":[[],[],[],[],[],[],[]],"p2St
ats":[30.0,25.0,5.0,0],"events":{"selfDestruct":[],"breach":[],"damage":[],"shield":[],"move":[],"spawn":[],"death":[],"
attack":[],"melee":[]}}

{"p2Units":[[],[],[],[],[],[],[]],"turnInfo":[0,0,-1],"p1Stats":[30.0,25.0,5.0,0],"p1Units":[[],[],[],[],[],[],[]],"p2St
ats":[30.0,25.0,5.0,0],"events":{"selfDestruct":[],"breach":[],"damage":[],"shield":[],"move":[],"spawn":[],"death":[],"
attack":[],"melee":[]}}

Player0 punished because took too long. Time (ms): 51519 Dmg: 31
Player1 punished because took too long. Time (ms): 51440 Dmg: 31
Winner (p1 perspective, 1 = p1 2 = p2): 2
PLAYER 2 WINS!
Waiting to exit finished game.
sent game end playerIndex: 0
sent game end playerIndex: 1
sent game end playerIndex: 0
SAPlayer 2 starter-algo: C:\Program Files\Python36\python.exe: can't open file '\algo_strategy.py': [Errno 2] No such fi
le or directory
sent game end playerIndex: 1
Done waiting now exiting finished game.
Hard Exiting Now
Closing stream
freeze 3644java.io.IOException: Cannot run program "kill": CreateProcess error=2, Sistemul nu poate găsi fi?ierul specif
icat
        at java.base/java.lang.ProcessBuilder.start(Unknown Source)
        at java.base/java.lang.ProcessBuilder.start(Unknown Source)
        at java.base/java.lang.Runtime.exec(Unknown Source)
        at java.base/java.lang.Runtime.exec(Unknown Source)
        at java.base/java.lang.Runtime.exec(Unknown Source)
        at util.ProcessUtil.freezeProcessTree(ProcessUtil.java:23)
        at util.ProcessUtil.killRecursive(ProcessUtil.java:11)
        at towergame.gamecore.player.SimpleAlgoPlayer.close(SimpleAlgoPlayer.java:201)
        at towergame.gamecore.player.PlayerManager.closeAllPlayers(PlayerManager.java:36)
        at towergame.GameMain.processEndGame(GameMain.java:547)
        at towergame.GameMain.runLoop(GameMain.java:401)
        at towergame.GameMain.startGame(GameMain.java:202)
        at towergame.GameMain.main(GameMain.java:175)
        at towerworker.TowerWorker.main(TowerWorker.java:78)
Caused by: java.io.IOException: CreateProcess error=2, Sistemul nu poate găsi fi?ierul specificat
        at java.base/java.lang.ProcessImpl.create(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
        at java.base/java.lang.ProcessImpl.start(Unknown Source)
        ... 14 more

kill 3644
Closing playerIndex: 0
Closing stream
freeze 3244java.io.IOException: Cannot run program "kill": CreateProcess error=2, Sistemul nu poate găsi fi?ierul specif
icat
        at java.base/java.lang.ProcessBuilder.start(Unknown Source)
        at java.base/java.lang.ProcessBuilder.start(Unknown Source)
        at java.base/java.lang.Runtime.exec(Unknown Source)
        at java.base/java.lang.Runtime.exec(Unknown Source)
        at java.base/java.lang.Runtime.exec(Unknown Source)
        at util.ProcessUtil.freezeProcessTree(ProcessUtil.java:23)
        at util.ProcessUtil.killRecursive(ProcessUtil.java:11)
        at towergame.gamecore.player.SimpleAlgoPlayer.close(SimpleAlgoPlayer.java:201)
        at towergame.gamecore.player.PlayerManager.closeAllPlayers(PlayerManager.java:36)
        at towergame.GameMain.processEndGame(GameMain.java:547)
        at towergame.GameMain.runLoop(GameMain.java:401)
        at towergame.GameMain.startGame(GameMain.java:202)
        at towergame.GameMain.main(GameMain.java:175)
        at towerworker.TowerWorker.main(TowerWorker.java:78)
Caused by: java.io.IOException: CreateProcess error=2, Sistemul nu poate găsi fi?ierul specificat
        at java.base/java.lang.ProcessImpl.create(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
        at java.base/java.lang.ProcessImpl.start(Unknown Source)
        ... 14 more

kill 3244
Closing playerIndex: 1
Exited for loop
End of main
Closing stream
freeze 3644java.io.IOException: Cannot run program "kill": CreateProcess error=2, Sistemul nu poate găsi fi?ierul specif
icat
        at java.base/java.lang.ProcessBuilder.start(Unknown Source)
        at java.base/java.lang.ProcessBuilder.start(Unknown Source)
        at java.base/java.lang.Runtime.exec(Unknown Source)
        at java.base/java.lang.Runtime.exec(Unknown Source)
        at java.base/java.lang.Runtime.exec(Unknown Source)
        at util.ProcessUtil.freezeProcessTree(ProcessUtil.java:23)
        at util.ProcessUtil.killRecursive(ProcessUtil.java:11)
        at towergame.gamecore.player.SimpleAlgoPlayer.close(SimpleAlgoPlayer.java:201)
        at towergame.GameMain.main(GameMain.java:177)
        at towerworker.TowerWorker.main(TowerWorker.java:78)
Caused by: java.io.IOException: CreateProcess error=2, Sistemul nu poate găsi fi?ierul specificat
        at java.base/java.lang.ProcessImpl.create(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
        at java.base/java.lang.ProcessImpl.start(Unknown Source)
        ... 10 more

kill 3644
Closing stream
freeze 3244java.io.IOException: Cannot run program "kill": CreateProcess error=2, Sistemul nu poate găsi fi?ierul specif
icat
        at java.base/java.lang.ProcessBuilder.start(Unknown Source)
        at java.base/java.lang.ProcessBuilder.start(Unknown Source)
        at java.base/java.lang.Runtime.exec(Unknown Source)
        at java.base/java.lang.Runtime.exec(Unknown Source)
        at java.base/java.lang.Runtime.exec(Unknown Source)
        at util.ProcessUtil.freezeProcessTree(ProcessUtil.java:23)
        at util.ProcessUtil.killRecursive(ProcessUtil.java:11)
        at towergame.gamecore.player.SimpleAlgoPlayer.close(SimpleAlgoPlayer.java:201)
        at towergame.GameMain.main(GameMain.java:178)
        at towerworker.TowerWorker.main(TowerWorker.java:78)
Caused by: java.io.IOException: CreateProcess error=2, Sistemul nu poate găsi fi?ierul specificat
        at java.base/java.lang.ProcessImpl.create(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
        at java.base/java.lang.ProcessImpl.start(Unknown Source)
        ... 10 more

kill 3244
```
How can i fix this so i can run tests on my machine?

**Comment by suppergerrie2** [comment]
Same issue here.
Using Windows 10.

**Comment by JeffreyO** [comment]
This is due to the applet trying to run the UNIX command "kill". It's bad for this sort of thing in Java due to it ruining the portability of the applet that Java allows.

**Comment by skelly1324** [comment]
This issue has been fixed, you can pull from the master branch to get the fixes.

**Comment by JeffreyO** [comment]
Confirming that the issue is fixed:

Run Log from run_match.ps1
...
Starting Engine
Starting single worker game.
D:\C1GamesStarterKit-master\algos\starter-algo-ZIPME\run.ps1
D:\C1GamesStarterKit-master\algos\starter-algo-ZIPME\run.ps1
Saving replay: D:\C1GamesStarterKit-master\replays\p1-11-10-2018-02-53-49-1539240829929-288226625.replay
P1 Name: starter-algo-ZIPME
P2 Name: starter-algo-ZIPME
Starting turn: 0
timed out
Last state:
{"p2Units":[[],[],[],[],[],[],[]],"turnInfo":[0,0,-1],"p1Stats":[30.0,25.0,5.0,0],"p1Units":[[],[],[],[],[],[],[]],"p2St
ats":[30.0,25.0,5.0,0],"events":{"selfDestruct":[],"breach":[],"damage":[],"shield":[],"move":[],"spawn":[],"death":[],"
attack":[],"melee":[]}}

timed out
Last state:
{"p2Units":[[],[],[],[],[],[],[]],"turnInfo":[0,0,-1],"p1Stats":[30.0,25.0,5.0,0],"p1Units":[[],[],[],[],[],[],[]],"p2St
ats":[30.0,25.0,5.0,0],"events":{"selfDestruct":[],"breach":[],"damage":[],"shield":[],"move":[],"spawn":[],"death":[],"
attack":[],"melee":[]}}

Player0 punished because took too long. Time (ms): 50015 Dmg: 30
Player1 punished because took too long. Time (ms): 50007 Dmg: 30
Winner (p1 perspective, 1 = p1 2 = p2): 2
PLAYER 2 WINS!
Waiting to exit finished game.
sent game end playerIndex: 0
sent game end playerIndex: 1
sent game end playerIndex: 0
sent game end playerIndex: 1
Done waiting now exiting finished game.
Hard Exiting Now
Closing stream
kill 4136
Closing playerIndex: 0
Closing stream
kill 10516
Closing playerIndex: 1
Exited for loop
End of main
Closing stream
kill 4136
Closing stream
...
